Ccontact form
Isabellanamutenda/Portfolio pull request #3
Opened 2021-07-20 21:31 UTC by Isabellanamutenda

- I added the contact form according to the instructions
- I styled the mobile version

2021-07-20 22:51 UTC, mimipeshy commented
## Hi @Isabellanamutenda and @mwanawabangona 👋🏾 👋🏾 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have a README file making your PR unprofessional. Add a descriptive README file to your project - please use [this template](https://github.com/microverseinc/readme-template) but remember to customize it to your project.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2021-07-21 07:26 UTC, mikenath223 commented
Hi , 

You made a great effort in this project, but unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that will be invalidated for this reason:
-  Kindly ensure all GitHub linting checks pass.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Happy coding. Cheers!🚀🚀

If something isn't 100% clear, you can leave comments or questions in this PR thread.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, whether valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **don't count** into the code reviews limit._

2021-07-21 07:55 UTC, arslanbisharat requested changes
# Changes Requested, 

Hi @Isabellanamutenda, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-07-21 07:55 UTC, arslanbisharat commented on index.html
> +      <form action="#" method="post">
- [ ] Please make sure the form uses the `action` attribute to integrate with formspree service & `action` value should be similar to `https://formspree.io/f/{form_id}`

2021-07-21 07:55 UTC, arslanbisharat commented on index.html
> +          <button type="submit">Get in touch</button>
- [ ] Make sure the project has button interactions such as hover, active (when it's pressed), disabled and enable (default state) are styled as shown in the Figma template.

2021-07-21 08:52 UTC, Isabellanamutenda commented on index.html
> +      <form action="#" method="post">
Resolved

2021-07-21 09:26 UTC, Isabellanamutenda commented on index.html
> +          <button type="submit">Get in touch</button>
Resolved

2021-07-21 09:50 UTC, mikenath223 approved these changes
Hello there  

Your project is complete!  There is nothing else to say other than... it's time to merge it 🛳 
Congratulations! 🎉 

Happy coding. Cheers! 🚀🚀

If you feel something isn't clear enough you can leave a question or comment in the PR thread.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-21 09:58 UTC, merged